In [2]:
import nltk

In [3]:
a=['cat stunts','cat dog','mouse jumps stunts']

In [5]:
!python3.14 -m pip install scikit-learn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'sklearn' when getting requirements to build wheel

^C

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\kriti\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\kriti\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.6.0)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\kriti\AppData\Roaming\Python\Python314\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.4 MB 6.3 MB/s eta 0:00:02
   ---------------------- ----------------- 4.7/8.4 MB 10.5 MB/s eta 0:00:01
   --------------------------------- ------ 7.1/8.4 MB 11.2 MB/s eta 0:00:01
   -------------------------------------- - 8.1/8.4 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 8.4/8.4 MB 9.0 MB/s  0:00:01
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   --- ------------------------------------ 3.1/37.4 MB 17.5 MB/s eta 0:00:02
   ------- -------------------------------- 7.1/37.4 MB 17.7 MB/s eta 0:00:02
   ----------- ---------------------------- 10.7/37.4 MB 17.6 MB/s eta 0:00:02
   ------------ --------------------------- 11.8/37.4 MB 16.6 MB/s eta 0:00:02
   --------------- ------------------------ 14.2/37.4 MB 13.6 MB/s eta 0:00:02
   ------------------ --------------------- 17.6/37.4 MB 14.0 MB/s eta 0:00:02
   ---------------------- ----------------- 21.2/37.4 MB 14.6 MB/s eta 0:00:02
   ------------------------- -------------- 23.6/37.4 MB 14.0 MB/s eta 0:00:01
   ---------------------------- ----------- 26.5/37.4 MB 14.0 MB/s eta 0:00:01
   -------------------------------- ------- 30.1/37.4 MB 14.3 MB/s eta 0:00:01
   ----------------------------------- ---- 33.6/37.4 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.4 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.4 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.4 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------- 37.4/37.4 MB 12.0 MB/s  0:00:03
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed narwhals-2.27.1 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

In [1]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [4]:
cv=CountVectorizer()

In [5]:
cv.fit_transform(a).toarray()

array([[1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1]])

In [6]:
cv.get_feature_names_out()

array(['cat', 'dog', 'jumps', 'mouse', 'stunts'], dtype=object)

In [7]:
import pandas as pd

In [8]:
pd.DataFrame(cv.fit_transform(a).toarray(),columns=cv.get_feature_names_out(), index=a)

                    cat  dog  jumps  mouse  stunts
cat stunts            1    0      0      0       1
cat dog               1    1      0      0       0
mouse jumps stunts    0    0      1      1       1

In [9]:
import math

In [10]:
math.log(3/2)

0.4054651081081644

In [12]:
(1/2)*(math.log(3/2))

0.2027325540540822

In [11]:
tv=TfidfVectorizer()

In [12]:
tv.fit_transform(a).toarray()

array([[0.70710678, 0.        , 0.        , 0.        , 0.70710678],
       [0.60534851, 0.79596054, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.62276601, 0.62276601, 0.4736296 ]])

In [13]:
df = pd.read_csv("IMDB Dataset.csv")

In [18]:
#Naive bayes algorithm

In [19]:
#Bayes theorem

In [17]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [14]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

In [15]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(418)

In [17]:
import imblearn

In [18]:
ros=imblearn.over_sampling.RandomOverSampler()

In [19]:
len(df)

50000

In [20]:
x=df[['review']]
y=df[['sentiment']]

In [21]:
x,y=ros.fit_resample(x,y)

In [22]:
from collections import Counter

In [23]:
c=Counter(y)

In [24]:
c

Counter({'sentiment': 1})

In [25]:
df.duplicated().sum()

np.int64(418)

In [26]:
import re

In [27]:
from nltk.tokenize import word_tokenize

In [28]:
from nltk.corpus import stopwords

In [29]:
from nltk.stem import WordNetLemmatizer

In [30]:
def preprocessing(x):
    x=x.lower()
    x=word_tokenize(x)
    y=[i for i in x if i.isalpha()]
    return ' '.join(y)

In [31]:
def swr(x):
    sws = stopwords.words('english')
    z=[]
    x=x.split()
    for i in x:
        if i not in sws:
            z.append(i)
    return ' '.join(z)

In [32]:
wnl=WordNetLemmatizer()

In [33]:
wnl.lemmatize('plays')

'play'

In [34]:
def lem(x):
    wnl=WordNetLemmatizer()
    y=[]
    x=x.split()
    for i in x:
        y.append(wnl.lemmatize(i))
    return ' '.join(y)

In [35]:
df['review'] = df['review'].map(preprocessing)
df['review'] = df['review'].map(swr)

In [36]:
df['review']=df['review'].map(lem)

In [37]:
df

                                                  review sentiment
0      one reviewer mentioned watching oz episode hoo...  positive
1      wonderful little production br br filming tech...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically family little boy jake think zombie ...  negative
4      petter mattei love time money visually stunnin...  positive
...                                                  ...       ...
49995  thought movie right good job creative original...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary school nu...  negative
49998  going disagree previous comment side maltin on...  negative
49999  one expects star trek movie high art fan expec...  negative

[50000 rows x 2 columns]

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le=LabelEncoder()
df['sentiment']=le.fit_transform(df['sentiment'])

In [41]:
x=df['review']
y=df['sentiment']

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=40)

In [43]:
tv=TfidfVectorizer()

In [44]:
x_train = tv.fit_transform(x_train)

In [45]:
x_test = tv.transform(x_test)

In [46]:
from sklearn.naive_bayes import MultinomialNB

In [47]:
model=MultinomialNB()

In [48]:
model.fit(x_train, y_train)

MultinomialNB()

In [53]:
pred=model.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [52]:
accuracy_score(y_test, pred)

0.8613

In [54]:
confusion_matrix(y_test, pred)

array([[4454,  646],
       [ 741, 4159]])

In [55]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.86      0.87      0.87      5100
           1       0.87      0.85      0.86      4900

    accuracy                           0.86     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000

In [56]:
rv=df['review'].loc[1]

In [57]:
rv

'wonderful little production br br filming technique fashion give comforting sometimes discomforting sense realism entire piece br br actor extremely well michael sheen got polari voice pat truly see seamless editing guided reference williams diary entry well worth watching terrificly written performed piece masterful production one great master comedy life br br realism really come home little thing fantasy guard rather use traditional dream technique remains solid disappears play knowledge sens particularly scene concerning orton halliwell set particularly flat halliwell mural decorating every surface terribly well done'

In [58]:
model.predict(tv.transform([rv]))

array([1])